### ISSUE TITLE
Ubuntu 15.10 Error

### ISSUE THREAD

**Issue by scriptzteam** [Swizards/QuickBox#14]
scriptzteam@xyz:~$ sudo quickbox
>>> /etc/sudoers: syntax error near line 20 <<<
sudo: parse error in /etc/sudoers near line 20
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin

now i can not SUDO !!!

**Comment by JMSDOnline** [comment]
```apt-get install sudo```
It looks like your server requires it to be installed first. I'll double check dependencies.

**Comment by JMSDOnline** [comment]
No details or follow response :: closing
