### ISSUE TITLE
sudoers

### ISSUE THREAD

**Issue by RXWatcher1** [Swizards/QuickBox#16]
isnt the
user ALL=(ALL:ALL) NOPASSWD: ALL
www-data     ALL=(ALL:ALL) NOPASSWD: ALL

a very large security risk? You're basically giving those users full access to run all commands without prompting. As a test, I was able to use 'sudo apt-get update' and 'sudo reboot' as the user.

I am more concerned about www-data having that ability than my master user.

**Comment by JMSDOnline** [comment]
If this were intended as a commercial application, then yes... www-data would hold no sudo privileges and only a set line of commands would be given sudo access. However, this is not a commercial application and this is intended for single-user (and though it is multi-user friendly - you should be mindful of who you share your server with) use... thus, it's like saying it is insecure to the root account itself.

However, this is something any user can change in accordance with their own needs, I merely presented it this way (again) for single users to have powers granted to their dashboard.

Feel free to fork and submit a pull request for your enhancements! :smile:

**Comment by JMSDOnline** [comment]
Also, please bare in mind.. this is a public sandbox and it is intended only as an example platform. This is not a reflection of the actual Swizards setup within their infrastructure on paid-for services. This is meant to be adapted by the users that use the script.

**Comment by RXWatcher1** [comment]
I understand. I just found this yesterday and loaded it on a VM locally to compare, not on my server in the wild.

It is significantly different than the swizards setup on my current seedbox which uses laravel.

My intent is actually to fork/pull as I have time to improve it. I would like to see more addons like the plex/btsync and I noticed the " web console" for my user is broken. I'm not sure of its purpose.

I do like the design. I just installed it last night so I havent had much time to dig into how it functions yet. That will be the first effort, understanding how the panel works in order to enhance.

Thanks  for releasing this.

**Comment by JMSDOnline** [comment]
@RXWatcher1 , I really appreciate any of your reports that you have time to submit. This is far different in comparison.. and you are right, there are a few features and enhancements that users would like to see. The big goal is to have this as a means for the community to play around and potentially produce a "panel by the people for the people" project for a wonderful community.

The Swizards panel itself is in top secret (@kclawl might scold me for merely mentioning it :stuck_out_tongue:  ) development and is being rehashed. No ETA on it... but in the meantime, we hope QuickBox is fun for everyone. Again, any enhancements you'd like to contribute while we steadily work on the new version (with loads of new features and data) at Swizards.. please submit your requests!

Happy coding and we look forward to anything you find and choose to include. :+1:

**Comment by RXWatcher1** [comment]
I have the utmost respect for @kclawl so if this project has his blessing then, I'll contribute as I can. Part of me wanted to make sure it was on the up and up and not working against him to try to take away from his efforts that he's already put in. I honestly wouldn't participate if that was the case.

**Comment by JMSDOnline** [comment]
Absolutely and thank you for the respect... myself and @kclawl are in daily/hourly contact. Thanks for your support!
