### ISSUE TITLE
Not working version check

### ISSUE THREAD

**Issue by bsormagec** [Swizards/QuickBox#17]
[https://github.com/Swizards/QuickBox/blob/master/quickbox.sh#L46-L49](url)

version check script for /usr/bin/quickbox not working its writing into file Not Found only please fix that

**Comment by JMSDOnline** [comment]
Thank you for your report @bsormagec! I have removed the version check line as it is no longer needed. The version can be found under the username dropdown (top right). There will be more adjustments to this at a later time.

**Comment by bsormagec** [comment]
You are wellcome! @JMSDOnline, when i have some free time i will be develop something for this project but you make really good job with this project thanks for everything.
