### ISSUE TITLE
Logs auth.log

### ISSUE THREAD

**Issue by Setsuneh** [Swizards/QuickBox#22]
Hi !

With a _cat /var/log/auth.log_, I've got a lot of strange reports. How resolve it?

> Feb 26 02:24:58 sd-45406 sudo: www-data : TTY=unknown ; PWD=/srv/rutorrent/home/req ; USER=root ; COMMAND=/usr/sbin/repquota /
> Feb 26 02:24:58 sd-45406 sudo: www-data : TTY=unknown ; PWD=/srv/rutorrent/home/req ; USER=root ; COMMAND=/usr/sbin/repquota /
> Feb 26 02:24:58 sd-45406 sudo: www-data : TTY=unknown ; PWD=/srv/rutorrent/home/req ; USER=root ; COMMAND=/usr/sbin/repquota /
> Feb 26 02:24:59 sd-45406 sudo: www-data : TTY=unknown ; PWD=/srv/rutorrent/home/req ; USER=root ; COMMAND=/usr/bin/cut -d. -f1 /proc/uptime
> 

This problem results about when i'm connected on the GUI Plateforme only.

**Comment by Setsuneh** [comment]
UP.

**Comment by RXWatcher1** [comment]
So you dont want the sudo commands to show up in the auth.log? That is very dangerous.

You need to dig into how this GUI works. The gui runs as the www-data user and then uses sudo to execute commands that need to be run as root. If you look at /etc/sudoers you'll see that the www-data user has the ability to run ALL commands as root without being prompted for the www-data password. This is massively dangerous. A hacker could basically take over the server if they can get the GUI to execute some sudo commands. You could limit the programs/commands that the www-data user could run via sudo but its not setup that way. It's setup to allow www-data to execute all the commands that root can execute without being prompted.

I would not run this system in the wilds of the internet without taking the time to understand it and locking it down.

**Comment by JMSDOnline** [comment]
Thanks @RXWatcher1!

I am actually going to be releasing an update by the end of this weekend that addresses these security concerns. The update will involve a restructuring of the template as well as setting only a limited amount of commands that www-data may perform. 

@Setsuneh, be on the lookout for the update in case you are still in need of this... and yes, those logs are merely documenting all the commands that are being made by www-data. It's good practice (typically) to always be aware (to prevent hijacking) of what is being ran on a system level. 

That being said, what you are seeing there is an example of www-data running quotas against user accounts as root as www-data by default has ALL:ALL privs... again, this will be fixed within the next 2 days.


Thanks for being a part of Swizards QuickBox project! :smile_cat:
