### ISSUE TITLE
BT Sync won't start

### ISSUE THREAD

**Issue by warplayer** [Swizards/QuickBox#23]
I click on the slider to turn BT Sync on, the page reloads and I get the message "Hey warplayer: Im going to enable btsync ... Please allow 5 minutes for it to start ... " but the BTSync slider stays grey and the service never starts.

I could always just install BT Sync myself, but I really want to have it controllable from my QuickBox dashboard. Please help, thank you.

**Comment by warplayer** [comment]
Sorry, I got it running now. I just uninstalled then reinstalled BTSync through the Quickbox dashboard and it is now running. Only thing is, now I can't connect! I tried the default port of 8888 but it's not working. What port is it running on?

**Comment by Farquaad56** [comment]
same problem BTSync doesn't start and work out of the box

**Comment by warplayer** [comment]
I ended up just loading my own install of BTSync in another directory on my seedbox. It's working great, but I would much rather use my QuickBox install so I can make use of the On/Off button on the Dashboard.

**Comment by JMSDOnline** [comment]
Thanks for the updates... I am now back from some extended /away time. I'll look into these issues here in the next couple of days. I have a few things that need to be addressed in the script... shouldn't be hard at all to implement an update either, so stay tuned. :smile_cat:

**Comment by warplayer** [comment]
Thanks for responding, that's fantastic! I was wondering how I was going to get this working without having to run the whole Quickbox install. Btw I'm really loving the whole setup you've created here, great work.
