### ISSUE TITLE
Issue with Disk space view

### ISSUE THREAD

**Issue by gokudarkaqw** [Swizards/QuickBox#35]
Hello,

Just installed your wonderfull auto-script on a fresh debian 7.

I got this issue with disk space view : http://prntscr.com/ahfwx1
Besides, i don't have a /home partition, all is set on / as you can : 
[root@seedbox]:(1.0Mb)~# df -h
Sys. fich.                                             Taille Util. Dispo Uti% MontÃ© sur
rootfs                                                   292G  3,5G  274G   2% /
udev                                                      10M     0   10M   0% /dev
tmpfs                                                    202M  412K  201M   1% /run
/dev/disk/by-uuid/39e6ed83-68b3-48cd-bb45-9733f47579e5   292G  3,5G  274G   2% /
tmpfs                                                    5,0M     0  5,0M   0% /run/lock
tmpfs                                                    1,2G  4,0K  1,2G   1% /run/shm
cgroup                                                    12K     0   12K   0% /sys/fs/cgroup
cgmfs                                                    100K     0  100K   0% /run/cgmanager/fs
tmpfs                                                    202M     0  202M   0% /run/user/0

Config file looks fine : 
  $topDirectory = '/home/xxx/';

Do you have any idea on how to fix it ? Your work is quite impressive !

**Comment by JMSDOnline** [comment]
@gokudarkaqw, make sure you do an initial quota limit for the user.

Type ``setdisk`` from the command line and you can enter in the limits.

Please shout if there is anything else... also, thanks for the compliment! :smile_cat:

**Comment by gokudarkaqw** [comment]
Works perfectly fine now :D Thank you a lot for this quick answer !! 

Keep up the good work !
