### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by demonotaku** [Swizards/QuickBox#36]
Cloning into '/root/tmp/QuickBox'...
remote: Counting objects: 3787, done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 3787 (delta 53), reused 0 (delta 0), pack-reused 3663
Receiving objects: 100% (3787/3787), 53.68 MiB | 877.00 KiB/s, done.
Resolving deltas: 100% (890/890), done.
Checking connectivity... done.
quickbox.sh: line 1183: syntax error near unexpected token `done'
quickbox.sh: line 1183: `done'

**Comment by JMSDOnline** [comment]
What OS/Distro are you getting this error on? I will attempt to reproduce quickly.

**Comment by demonotaku** [comment]
Ubuntu 15.10

**Comment by JMSDOnline** [comment]
@demonotaku, you may want to rm -rf that ``/root/tmp/`` directory and reinstall. I just scanned through the script and fixed a number of queues that were out of sorts after the last big version update.

**Comment by demonotaku** [comment]
I cleared the tmp after i got done with dinner about 10-20 minutes ago to
fix the script issue

If you advise me to start over I will.

**Comment by JMSDOnline** [comment]
Yes, I suggest you re-download the repo and run the install once more. It should complete without issue. I just ran it on Ubuntu 14.04 - 15.10 as well as Debian 8 and had no complaints. :smile_cat:

**Comment by demonotaku** [comment]
Cool; redoing my server then i got to start building my ultra box :100:
