### ISSUE TITLE
Error when installing dependencies ( _depends )

### ISSUE THREAD

**Issue by Keevar** [Swizards/QuickBox#42]
Hello.
Sorry, I do speak little English.
I hope I will get to explain my problem.

The person who showed me the software has the same problem.

I'm on Debian 8.4 (jessie) http://prntscr.com/ano0bv
I try to install QuickBox, but it does not work.
The installation seems to be fine, but not much has been installed.

I gave my server 0, then I deleted `>>"${OUTTO}" 2>&1` the installation script for errors.
There is an error while apt-get. It can not find php5-geoip, so, it does not install any addiction but continuous precedure as if all was well.

Here is a screen of the error:
http://prntscr.com/annzeg

What to do ?

Thank you

**Comment by JMSDOnline** [comment]
Could you try the following:

``apt-get update --fix-missing``
followed by
``apt-get install php5-geoip``

See if this installs php5-geoip dependencies. I am going to review why these may be failing. Do you by chance have a server with ipv6 enabled?

**Comment by Keevar** [comment]
My installation is clean (just reinstall before using the script), I can't have dependency Blublu program.


Yes I had a IPv6. I disable, but it made no difference to the problem. (I used your two commands before and after disabling IPv6)
http://prntscr.com/ao3yua


It does not come from the SED distribution (testing)? The package may have changed, as we move on the testing branch, and that packets can change and between bugger.
Why not stay on the stable branch of Debian?

**Comment by JMSDOnline** [comment]
@Keevar, thank you for pointing that out... the testing branch on Debian builds will cause massive conflicts in Debian builds. I have commented it within the [development tree](https://github.com/Swizards/QuickBox/tree/development).

I am running a test build here in the next 5 minutes to trial some issues for fixing. Thank you for bringing this to my attention once more.

**Comment by Keevar** [comment]
Thank you, everything works
