### ISSUE TITLE
VSFTPD wont start

### ISSUE THREAD

**Issue by RaymondSchnyder** [Swizards/QuickBox#51]
Hey Quickbox developer team,
me again, found another "bug" (maybe its a bug which i produced accidentally)

The FTP service  (vsftpd) wont start.
 The log file (/var/log/vsftpd.log) is empty and the config looks correct.

Is there any other logfile i didnt see?

Regards
Raymond

**Comment by JMSDOnline** [comment]
Hello again @RaymondSchnyder,

Are the results better if you try ...
``sudo /etc/init.d/vsftpd restart``

**Comment by RaymondSchnyder** [comment]
Nope, didnt work 

> [root@media]:(79.3kb)/var/www# sudo /etc/init.d/vsftpd restart
Stopping FTP server: No /usr/sbin/vsftpd found running; none killed.
vsftpd.
Starting FTP server: vsftpd.
[root@media]:(79.3kb)/var/www# sudo /etc/init.d/vsftpd status
vsftpd is not running
[root@media]:(79.3kb)/var/www#

Thats the result i get

**Comment by JMSDOnline** [comment]
That's no good. What does ``ls -l /etc/init.d/vsftpd`` that command return?

**Comment by RaymondSchnyder** [comment]
> [root@media]:(17.2Mb)/var/log/apache2# ls -l /etc/init.d/vsftpd
-rwxr-xr-x 1 root root 2321 Jan  8  2012 /etc/init.d/vsftpd
[root@media]:(17.7Mb)/var/log/apache2#

Returns that. (here as picture: http://i.imgur.com/LRqE8uK.png)

**Comment by JMSDOnline** [comment]
Awesome! Now let us try the next command and see what it returns: ``ls -l /usr/sbin/vsftpd``

**Comment by RaymondSchnyder** [comment]
> [root@media]:(0b)/srv# ls -l /usr/sbin/vsftpd
-rwxr-xr-x 1 root root 163944 Mar  4  2012 /usr/sbin/vsftpd
[root@media]:(0b)/srv#
 Picture: http://i.imgur.com/5VQCsIm.png

Thanks alot for helping me, you are really nice :-)

**Comment by JMSDOnline** [comment]
When you try to connect via FTP, does it return anything in particular?

**Comment by RaymondSchnyder** [comment]
http://i.imgur.com/MplgilN.png here is a picture of the ftp client. It doesnt return anything, because i cant start vsftpd

**Comment by JMSDOnline** [comment]
Right, I just need to verify. It looks like there is actually an issue with vsftpd itself. In the meantime, you can connect via port 4747 [SFTP] - I am going to mark this as a bug and look into this a bit later when I have more time. I can confirm that even on user creation, it is not properly adding users to the file for connect.

**Comment by JMSDOnline** [comment]
@RaymondSchnyder, could you please attempt the following. I found that the issues stated by yourself and what I would encounter are two separate problems. See #56 for the scenario we were facing. VSFTPd is however, running without issue.

Try this:

```
apt-get purge -y --force-yes vsftpd
apt-get install -y --force-yes vsftpd
cat >/etc/vsftpd.conf<<'VSD'
listen=YES
anonymous_enable=NO
guest_enable=NO
dirmessage_enable=YES
dirlist_enable=YES
download_enable=YES
secure_chroot_dir=/var/run/vsftpd/empty
chroot_local_user=YES
chroot_list_file=/etc/vsftpd.chroot_list
passwd_chroot_enable=YES
allow_writeable_chroot=YES
pam_service_name=vsftpd
ssl_enable=YES
allow_anon_ssl=NO
force_local_data_ssl=NO
force_local_logins_ssl=NO
ssl_tlsv1=YES
ssl_sslv2=NO
ssl_sslv3=NO
require_ssl_reuse=NO
ssl_request_cert=YES
ssl_ciphers=HIGH
rsa_cert_file=/etc/ssl/private/vsftpd.pem
local_enable=YES
write_enable=YES
local_umask=022
max_per_ip=0
pasv_enable=YES
port_enable=YES
pasv_promiscuous=NO
port_promiscuous=NO
pasv_min_port=0
pasv_max_port=0
listen_port=5757
pasv_promiscuous=YES
port_promiscuous=YES
seccomp_sandbox=no
VSD
```

Now create the needed chroot file for users...
```
echo "" > vsftpd.chroot_list
```

Now restart the services...
```
service vsftpd restart
service apache2 restart
```


Please let me know if this helps. Additionally, as per the commit that I attached on top of this message. Add your user (just the username) to the file you created --> /etc/vsftpd.chroot_list

**Comment by RaymondSchnyder** [comment]
I try this immediatly soon as i can! will be reporting if it works!

**Comment by RaymondSchnyder** [comment]
THIS WORKED!! Wow thank you! This patch worked for me!
Thank you for your amazing work! keep going!
