### ISSUE TITLE
"System Response"

### ISSUE THREAD

**Issue by RaymondSchnyder** [Swizards/QuickBox#52]
I see no text on your github site which explains what this function do.
I thought i can send users with "mail" mails and they can read it, but that would be weird.
Is there a documentation i didnt find / see?

Thank you for your nice script.

I wish you a great day

Regards 
Raymond

**Comment by JMSDOnline** [comment]
System Response within the Dashboard is exactly that... it is a simple response field for the systems response to various tasks/functions committed when you interact with the Panel. It does not mail users.

I assume this is what you are implying you think this does.
