### ISSUE TITLE
Forbidden Syntax

### ISSUE THREAD

**Issue by RaymondSchnyder** [Swizards/QuickBox#57]
Hello developers, wow my 4. issue today.

Soo i have a question about this jail you did for the users.
One of my users would like to start an SH File, but he cant because he has not the permssion to do this syntax: ./ServerStart.sh

> timo:~/Minecraft$ ./ServerStart.sh
*** forbidden syntax: ./ServerStart.sh
timo:~/Minecraft$

Is there a possibilty i can add a exception for a user or to remove the restriction with "./"?

Sorry for annoying you with thousand requests, i hope you are not stressed too much.

Regards Raymond

**Comment by JMSDOnline** [comment]
Yes, you can permit whichever commands you would like. 

You can modify the restrictions within the **lshell.conf** file located at ``/etc/lshell.conf``

> Disclaimer: Please be aware that allowing certain commands and functions such as vim, vi, ., ./ etc. may pose a security risk to your server environment, thus, allowing a more savvy friend to jailbreak from their shell and prank your server.

**Comment by RaymondSchnyder** [comment]
Okay, thank you for your answer. Good for me that i dont have savvy friends

**Comment by RaymondSchnyder** [comment]
I cant find the file you mentioned, is the path you gave me correct?
